image: atlassian/default-image:3

pipelines:
  branches:
    develop:
      - parallel:
        - step:
            name: '[lib-user]'
            script:
              - ./scripts/outputToSlack "lib-user" "Code analysis" "cd lib-user; ./gradlew ktlintCheck"
              - ./scripts/outputToSlack "lib-user" "Build and test" "cd lib-user; ./gradlew build"
        - step:
            name: '[ms-user]'
            script:
              - ./scripts/outputToSlack "ms-user" "Code analysis" "cd ms-user; ./gradlew ktlintCheck"
              - ./scripts/outputToSlack "ms-user" "Build and test" "cd ms-user; ./gradlew build"
