image: eclipse-temurin:17-jdk

pipelines:
  branches:
    develop:
      - parallel:
        - step:
            name: '[lib-user]'
            script:
              - wget https://raw.githubusercontent.com/Qrivi/handy-scripts/develop/outputToSlack.sh && chmod +x outputToSlack.sh # Get handy script
              - apt-get update && apt-get install -y jq git curl # Install jq, git and curl dependencies
              - ./lib-user/gradlew --version # Suppress version message in subsequent gradle output
              - ./outputToSlack.sh "lib-user" "Code analysis" "cd lib-user; ./gradlew ktlintCheck"
              - ./outputToSlack.sh "lib-user" "Build and test" "cd lib-user; ./gradlew build"
        - step:
            name: '[ms-user]'
            script:
              - wget https://raw.githubusercontent.com/Qrivi/handy-scripts/develop/outputToSlack.sh && chmod +x outputToSlack.sh # Get handy script
              - apt-get update && apt-get install -y jq git curl # Install jq, git and curl dependencies
              - ./ms-user/gradlew --version # Suppress version message in subsequent gradle output
              - ./outputToSlack.sh "ms-user" "Code analysis" "cd ms-user; ./gradlew ktlintCheck"
              - ./outputToSlack.sh "ms-user" "Build and test" "cd ms-user; ./gradlew build"
