image: eclipse-temurin:17-jdk

pipelines:
  branches:
    develop:
      - parallel:
        - step:
            name: '[lib-user]'
            script:
              - apt-get update && apt-get install -y jq git # Install jq and git dependencies
              - ./lib-user/gradlew --version # Suppress version message in subsequent gradle output
              - ./scripts/outputToSlack.sh "lib-user" "Code analysis" "cd lib-user; ./gradlew ktlintCheck"
              - ./scripts/outputToSlack.sh "lib-user" "Build and test" "cd lib-user; ./gradlew build"
        - step:
            name: '[ms-user]'
            script:
              - apt-get update && apt-get install -y jq git # Install jq and git dependencies
              - ./ms-user/gradlew --version # Suppress version message in subsequent gradle output
              - ./scripts/outputToSlack.sh "ms-user" "Code analysis" "cd ms-user; ./gradlew ktlintCheck"
              - ./scripts/outputToSlack.sh "ms-user" "Build and test" "cd ms-user; ./gradlew build"
