image: atlassian/default-image:3

pipelines:
  branches:
    develop:
      - parallel:
        - step:
            name: '[lib-user] Verify code quality and run tests'
            script:
              - cd lib-user
              - ./gradlew ktlintCheck
            after-script:
              - ./gradlew build # includes test
        - step:
            name: '[ms-user] Verify code quality and run tests'
            script:
              - cd ms-user
              - ./gradlew ktlintCheck
            after-script:
              - ./gradlew build # includes test
