apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: kareer/ms-user
      docker:
        dockerfile: Dockerfile
  local: {}

deploy:
  kubectl:
    manifests:
      - ../kareer-deploy/k8s/*.yml
      - ./k8s/*.yml
