kareer:
  consumer-id: localhost
  salt: $2a$12$d4cOXB.py0DYQh8ICeKdaejHycVpag.Mn1ZBR1SFwU5Agi2QP2O5O
  admin-email: kristof@kommaboard.be
  admin-password: KareerAdmin69
  confirm-email-ttl: 168 # hours aka 7 days
  reset-password-ttl: 24 # hours aka 1 day

server:
  port: 32002
  error:
    whitelabel:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: '*'

springdoc:
  api-docs:
    path: /openapi
  swagger-ui:
    path: /swagger

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kareer
    username: 'admin'
    password: 'admin'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        globally_quoted_identifiers: true
        jdbc:
          time_zone: UTC
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:/db/changelog.yml
  main:
    allow-bean-definition-overriding: true
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  output:
    ansi:
      enabled: always

logging:
  charset:
    console: UTF-8
    file: UTF-8
  file:
    name: log/ms-user.log
  level:
    root: INFO
    org.springframework: INFO
    org.springframework.web: DEBUG
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: INFO
    org.springframework.cloud.kubernetes.client.KubernetesClientUtils: ERROR
    io.kubernetes.client.spring.extended.controller.config.KubernetesInformerAutoConfiguration: ERROR
