apiVersion: v1
kind: Service
metadata:
  namespace: kareer
  name: ms-user
  labels:
    app: ms-user
spec:
  type: NodePort # ClusterIP
  selector:
    app: ms-user
  ports:
    - port: 32001
      nodePort: 32001
