apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kareer
  name: ms-user
  labels:
    app: ms-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-user
  template:
    metadata:
      labels:
        app: ms-user
    spec:
      containers:
        - name: ms-user
          image: kareer/ms-user
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 32001
