apiVersion: v1
kind: ConfigMap
metadata:
  namespace: kareer
  name: ms-user
  labels:
    app: ms-user
data:
  application.yml: |-
    spring:
      cloud:
        kubernetes:
          discovery:
            enabled: true
          loadbalancer:
            enabled: true
      datasource:
        url: jdbc:postgresql://ms-user-db:5432/kareer
        username: 'admin'
        password: 'admin'
