apiVersion: v1
kind: Service
metadata:
  namespace: kareer
  name: ms-user
  labels:
    app: ms-user
spec:
  type: ClusterIP
  selector:
    app: ms-user
  ports:
    - port: 32002
      targetPort: 32002
