kareer:
  config-server: http://kareer.internal:8002/api # TODO Use the most stable aka prod config server URL, once it's up

server:
  port: 8006
  servlet:
    context-path: /api
  error:
    whitelabel:
      enabled: false

spring:
  application:
    name: ms-user
  config:
    import: configserver:${kareer.config-server}
  cloud:
    kubernetes:
      loadbalancer:
        mode: service
      enabled: false
  rabbitmq:
    host: ${kareer.external.rabbitmq.host}
    port: ${kareer.external.rabbitmq.port}
    username: ${kareer.external.rabbitmq.username}
    password: ${kareer.external.rabbitmq.password}
    connection-timeout: 60000
  datasource:
    url: ${kareer.external.datasource.url}
    username: ${kareer.external.datasource.username}
    password: ${kareer.external.datasource.password}
    hikari:
      initialization-fail-timeout: 60000
  jpa:
    properties:
      hibernate:
        format_sql: true
        globally_quoted_identifiers: true
        jdbc:
          time_zone: UTC
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false
  liquibase:
    enabled: ${kareer.external.liquibase.enabled}
    drop-first: ${kareer.external.liquibase.drop-first}
    change-log: ${kareer.external.liquibase.change-log}
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  output:
    ansi:
      enabled: always

springdoc:
  api-docs:
    path: /openapi
  swagger-ui:
    path: /swagger

management:
  info:
    git:
      enabled: false
    java:
      enabled: true
    os:
      enabled: true
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
