kareer:
  consumer-id: ms-user@kareer.internal
  salt: $2a$12$d4cOXB.py0DYQh8ICeKdaejHycVpag.Mn1ZBR1SFwU5Agi2QP2O5O
  admin-email: kareer@kommaboard.be
  admin-password: KareerAdmin69
  confirm-email-ttl: 168 # hours aka 7 days
  reset-password-ttl: 24 # hours aka 1 day

server:
  port: 32002
  servlet:
    context-path: /api
  error:
    whitelabel:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: "*"

springdoc:
  api-docs:
    path: /openapi
  swagger-ui:
    path: /swagger

spring:
  rabbitmq:
    host: kareer.local
    port: 5672
    username: admin
    password: admin
    connection-timeout: 60000
  datasource:
    url: jdbc:postgresql://kareer.local:5432/kareer
    username: admin
    password: admin
    hikari:
      initialization-fail-timeout: 60000
  jpa:
    properties:
      hibernate:
        format_sql: true
        globally_quoted_identifiers: true
        jdbc:
          time_zone: UTC
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false
  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:/liquibase/changelog.yml
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  output:
    ansi:
      enabled: always

logging:
  charset:
    console: UTF-8
    file: UTF-8
  file:
    name: data/log/ms-user.log
  level:
    root: INFO
    org.springframework: INFO
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: INFO
    org.springframework.cloud.kubernetes.client.KubernetesClientUtils: ERROR
    io.kubernetes.client.spring.extended.controller.config.KubernetesInformerAutoConfiguration: ERROR

