name: Image creation

on:
  workflow_dispatch:
  push:
    branches: [ develop ]

env:
  REGISTRY: ghcr.io
  REGISTRY_USER: KommaBoard
  REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

jobs:
  dev-latest:
    name: dev-latest
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - name: Checkout codebase
        id: checkout-codebase
        uses: actions/checkout@v3.0.2
        with:
          ref: ${{ github.ref }}
      - name: Log in to registry
        id: login-to-registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
      - name: Extract version
        id: extract-version
        run: cat ./ms-user/build.gradle.kts | grep ^version | awk -F'"' '{print $2}' >> $GITHUB_OUTPUT
      - name: Extract metadata
        id: extract-metadata
        uses: docker/metadata-action@v4.3.0
        with:
          images: ${{ env.REGISTRY }}/kareer/ms-user
          flavor: |
            latest=auto
            prefix=dev-,onlatest=true
          tags: |
            type=semver,pattern={{version}},value=${{ steps.extract-version.outputs.version }}
      - name: Build and push image
        id: build-and-push-image
        uses: docker/build-push-action@v4.0.0
        with:
          context: ./ms-user
          push: true
          tags: ${{ steps.extract-metadata.outputs.tags }}
          labels: ${{ steps.extract-metadata.outputs.labels }}
      - name: Inform the team
        id: inform-team
        run: |
          curl -X POST -H "Content-type: application/json" --data "{
            \"blocks\": [
              {
                \"type\": \"section\",
                \"text\": {
                  \"type\": \"mrkdwn\",
                  \"text\": \"CI/CD built and pushed a new image! :whale:\"
                }
              },
              {
                \"type\": \"section\",
                \"fields\": [
                  {
                    \"type\": \"mrkdwn\",
                    \"text\": \"*Image*\n\`kareer/ms-user:dev-latest\`\"
                  },
                  {
                    \"type\": \"mrkdwn\",
                    \"text\": \"*Registry*\n<https://docker.qrivi.dev/v2/|docker.qrivi.dev> (private)\"
                  }
                ]
              }
            ]
          }" $SLACK_WEBHOOK_URL
